theme: jekyll-theme-minimal
title: Eddy Mendoza-Galindo
logo: eddy.jpg
description: I am an undergraduate researcher, illustrator and science communicator interested and motivated by plants. I am pursuing an Agri-Genomics bachelor's degree at UNAM (México) and am working on Agave and Saguaro's genomics.
[https://twitter.com/IamSomnya](Follow me on Twitter!)
