theme: jekyll-theme-minimal
title: Eddy Mendoza-Galindo
logo: eddy.jpg
description: I am a Master student in Evolutionary Biology (MEME), an illustrator and science communicator interested and motivated by plants.
