theme: jekyll-theme-minimal
title: Eddy Mendoza-Galindo
logo: pic.jpg
description: I am a undergraduate researcher, illustrator and science communicator interested and motivated by plants
background-image: agave.jpg
