theme: jekyll-theme-minimal
title: Eddy Mendoza-Galindo
logo: eddy.jpg
description: I am a student in the Erasmus Mundus Master Program in Evolutionary Biology, an illustrator and science communicator interested and motivated by plants.
